### ISSUE TITLE
Penamaan table

### ISSUE THREAD

**Issue by rgibranz** [noerfariss/pipos#1]
Banyak sih yang aku mau kasih masukan nih di project mas faris. tapi aku mau coba kasih masukan nih dari penamaan table di project ini. sebenernya masukan ku tuh berangkat dari niatan dari mas faris yang mau membuka project ini untuk umum, bukan cuma buat portofolio sendiri. dan juga untuk pengembangan skill mas faris juga.

![image](https://github.com/noerfariss/pipos/assets/43293928/0ab1ef65-44fc-4b0e-8499-c24a026be05a)

kalau dari yang aku liat mas faris nih bikin penamaan table pakai bahasa indonesia ya, contohnya pengaturans, kategoris dll. yang dimana ini mengikuti dari penamaan plural hasil generate command artisan. sebenernya penamaan seperti ini boleh boleh saja dan kalau dilihat ya berjalan oke. tapi memang penamaan ini harusnya menggunakan bahasa inggris supaya lebih terstandarisasi. 

beberapa referensi yang bisa di baca mas:
https://medium.com/@radiegtya/6-kesalahan-penamaan-dalam-mendesain-database-38a136dccf46
https://techarea.co.id/11-aturan-penting-dalam-perancangan-database/

**Comment by noerfariss** [comment]
Haloo mas Gibran terima kasih banyak atas masukannya.. saya sangat apresiasi dan tertarik untuk masukkan dalam list perubahan selanjutnya.

Yang saya tanyakan apakah hal tersebut hanya berkaitan dengan penamaan Database atau mencakup juga di Controller & Model?

**Comment by rgibranz** [comment]
iya mas itu berpengaruh juga nantinya. jadi menurutku ini menjadi hal yang perlu diperhatikan juga nih soal standarisasi. karena project yang open itu perlu standarisasi. jangan sampai semua programmer menuangkan semua se-enaknya aja

**Comment by noerfariss** [comment]
Baik mas, akan coba saya perbaiki next update.
Sekali lagi terima kasih masukkannya 👍
